resolver: lts-10.1
packages:
- '.'
- location:
    git: https://github.com/evturn/jaws
    commit: 2837b01b149de8617fcd5a6797a64ee191945ad7
extra-deps:
- git: git@github.com:evturn/jaws.git
  commit: 2837b01b149de8617fcd5a6797a64ee191945ad7
