export const GET_BOTS_BEGIN = 'GET_BOT_BEGIN';
export const GET_BOTS_SUCCESS = 'GET_BOT_SUCCESS';
export const GET_BOTS_ERROR = 'GET_BOT_ERROR';

export const GET_BLOG_POSTS_BEGIN = 'GET_BLOG_POSTS_BEGIN';
export const GET_BLOG_POSTS_SUCCESS = 'GET_BLOG_POSTS_SUCCESS';
export const GET_BLOG_POSTS_ERROR = 'GET_BLOG_POSTS_ERROR';